# Generated by Django 5.0.7 on 2025-09-07 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
