# Generated by Django 5.0.7 on 2025-09-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews_app", "0002_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="useful_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
