# Generated by Django 5.1.6 on 2025-10-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews_app", "0003_review_useful_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="text",
            new_name="comment",
        ),
        migrations.AddField(
            model_name="review",
            name="user_name",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
