# Generated by Django 5.0.7 on 2025-11-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews_app", "0007_rename_text_review_comment_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="review",
            name="user_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
