# Generated by Django 5.1.6 on 2025-10-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_review"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
