# Generated by Django 5.0.7 on 2025-10-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_delete_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="times_added_to_cart",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Veces añadido al carrito"
            ),
        ),
    ]
