# Generated by Django 5.0.7 on 2025-03-14 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_orders",
                to="orders.order",
            ),
        ),
    ]
