New-Item -ItemType Directory -Force .github | Out-Null
@"
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
"@ | Set-Content -Encoding UTF8 .github\dependabot.yml
